### ISSUE TITLE
Create overlay for bot

### ISSUE THREAD

**Issue by antter** [aicoe-aiops/github-labeler#109]
**Is your feature request related to a problem? Please describe.**
The bot needs to be deployed to openshit

**Describe the solution you'd like**
The best way to do this is probably to create an overlay for the bot so it's own image can be made and ArgoCD will create its pod.

**Comment by harshad16** [comment]
-[ ] step 1: 
create an directory called
`overlays`
inside it create two different sub directory: 
1. inference
2. bot

-[ ] step 2: 
move the pipfile and pipefile.lock into the inference
and the Dockerfile of the github-app into the bot

-[ ] step 3:
configure the Dockerfile , specifically for the github-app
that we can do , by making `workingdir: github-app` subdirectory, 

-[ ] step 4:
configure the .aicoe-ci.yaml
```
check:
  - overlays-build
overlays_dir: overlays
overlays:
  - name: inference
    build:
      build-stratergy: Source
      base-image: "quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.28.0"
      registry: quay.io
      registry-org: aicoe
      registry-project: github-labeler
      registry-secret: aicoe-pusher-secret

  - name: bot
    build:
      build-stratergy: Dockerfile
      registry: quay.io
      registry-org: aicoe
      registry-project: github-labeler-bot
      registry-secret: aicoe-pusher-secret
      custom-tag: latest
```
